# tasks file for haproxy
---
- name: configuration | update file
  template:
    src: "{{ haproxy_conf_template }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0640
    validate: "{{ haproxy_path }} -f %s -c"
  notify: restart haproxy
  tags:
    - haproxy-configuration-update-file
