# tasks file for haproxy
---
- name: install | add repository from PPA and install its signing key
  apt_repository:
    repo: "{{ haproxy_ppa_final }}"
    update_cache: true
  when: haproxy_use_ppa_final
  tags:
    - haproxy-install-add-repository

- name: install | dependencies
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies

- name: install | additional
  package:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ haproxy_install }}"
  tags:
    - haproxy-install-additional
