# tasks file for haproxy
---
- name: check version support
  fail:
    msg: "HAProxy version {{ haproxy_version }} is not supported"
  when: haproxy_version | string not in haproxy_versions_supported
  tags:
    - configuration
    - haproxy
    - haproxy-check-version-support

- name: Set version specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - configuration
    - haproxy
    - haproxy-set-version-specific-variables

- import_tasks: install.yml
  tags:
    - configuration
    - haproxy
    - haproxy-install

- import_tasks: certificates.yml
  tags:
    - configuration
    - haproxy
    - haproxy-certificates

- import_tasks: acl.yml
  tags:
    - configuration
    - haproxy
    - haproxy-acl

- import_tasks: configuration.yml
  tags:
    - configuration
    - haproxy
    - haproxy-configuration

- name: start and enable service
  service:
    name: haproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - haproxy
    - haproxy-start-enable-service
